name: Testing

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test mirror action
        uses: nobbs/action-mirror-action@v1.0.0
        with:
          token: ${{ secrets.PAT }}
          github-com-token: ${{ secrets.PAT }}
